### PR TITLE
add import curl request

### PR DESCRIPTION
**Pull request by jonrosner**

### CODE REVIEW

**Comment by arcastro** [comment]
@jonrosner , was looking for exactly this feature :)

Any reason it hasn't merged?

My main use-case is to copy curl-request from chrome developer tools (network tab) and have the ability to import the request onto Yaade.

**Comment by jonrosner** [comment]
It got lost in other features. It should be almost good to go though. I'll try to finish it up over the weekend.

**Comment by arcastro** [comment]
Ty for the tool! It's worked great so far, and I was pleasantly surprised that the two features I was missing already had pull requests open 😃

**Comment by jonrosner** [comment]
@arcastro merged the feature. You can update to the newest version, then create a new request and go to import. Simply paste in your curl and the request is parsed to a yaade request. It is a basic implementation, so more exotic features of curl might not be supported, but basic HTTP requests with URL, headers and body should be no problem.

**Pull request merged**
